spring.application.name=bookmarking

spring.profiles.active=local

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# DB Config
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JWT Secret Key
spring.jwt.secret=${JWT_SECRET}
spring.jwt.access-token-expiration-ms=3600000
spring.jwt.refresh-token-expiration-ms=604800000

# YouTube Data API Key
google.youtube.api.key=${YOUTUBE_API_KEY}

# R2 Config
cloud.r2.credentials.access-key=${R2_ACCESS_KEY_ID}
cloud.r2.credentials.secret-key=${R2_SECRET_ACCESS_KEY}
cloud.r2.bucket=marksphere-storage
cloud.r2.endpoint=${R2_ENDPOINT}

# AWS Lambda
aws.lambda.access-key=${AWS_ACCESS_KEY}
aws.lambda.scret-key=${AWS_SECRET_KEY}
aws.lambda.function-name=${LAMBDA_FUNCTION_NAME}

# Cloudflare CDN
cloudflare.cdn.domain=${CLOUDFLARE_CDN_DOMAIN}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=6379

# Batch
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true

server.forward-headers-strategy=native